#!/usr/bin/env python3


###############################################################################
###############################################################################
# Copyright (c) 2024, Andy Schroder
# See the file README.md for licensing information.
###############################################################################
###############################################################################




################################################################
# import modules
################################################################

# dc must be the first module initialized and then immediately set the mode
import dc,sys
dc.mode='GUI-test'

# dc.common must be the second imported module because it reads the config
from dc.common import GUI, logger, console

from time import sleep

console.setLevel('DEBUG')

ShutdownRequested=False



################################################################
# main loop
################################################################

while True:

	try:



	# shutdown logic

		if not ShutdownRequested and GUI.stopped() and not GUI.is_alive():
			logger.info('GUI triggered shutdown request')

			# need to re-call SystemExit outside of the thread
			sys.exit()

		# wait around until it is time to tell GUI to stop

		if GUI.is_alive():
			if ShutdownRequested:
				logger.error('threads did not shut down on their own, terminating them')
				break
			else:
				# nothing to do
				sleep(.1)
		else:
			if ShutdownRequested:
				logger.debug('threads shut down on their own after being asked')
				break
			else:
				logger.debug('threads shut down on their own without being asked')
				break

	except (KeyboardInterrupt, SystemExit):

		logger.info('shutdown requested')
		ShutdownRequested=True

		logger.debug('shutting threads down')
		GUI.stop()

		# note: .join(20) returns after 20 seconds OR when the thread joins/quits, whichever is sooner.
		# so, need to check .is_alive() above to see if the thread actually is still running.
		GUI.join(20)

		# now go up to (not GUI.is_alive()) and ShutdownRequested



logger.info('shutdown complete')
