
Seller:

        ##### common settings ####
        LNDhost:                          'lndconnect://<host>:<port>?[cert=<base64url DER certificate>&]macaroon=<base64url macaroon>'
        PrintWarningMessages:             True


        #### GRID related settings ####
        RemoteClientIdentifier:           'naLNM4EkYBLxJ510BrNLeyZukJWrAi'

        # LocalMeterNumber is the S/N printed on the front cover of the meter.
        LocalMeterNumber:                 '000300002157'

        LocalMeterScalingFactor:          1000.0

        RS485Port:                        '/dev/ttyAMA1'


        ##### EV related settings ####
        SWCANname:                        'can0'                                  #name of the interface for the single wire can bus, the charge port can bus.


Buyer:

        ##### common settings ####
        LNDhost:                          'lndconnect://<host>:<port>?[cert=<base64url DER certificate>&]macaroon=<base64url macaroon>'
        PrintWarningMessages:             True


        #### GRID related settings ####

        # LocalClientIdentifier should be a unique value randomly generated by the buyer or seller and given to the other party.
        # for the most part, it probably doesn't actually matter who generates it, as long as they both agree on the value through
        # some pre-existing secure communication (such as a physical site visit). it is used for the seller to identify (authenticate)
        # that the buyer that is connecting to them is a real customer and not just a random connection from some third party on the public internet.
        # the RemoteMeterNumber can't be used because it isn't unique enough of a value and the manufacturer knows the value.
        # also, future versions of Distributed Charge - GRID may allow a single payment module to buy energy from multiple meters.
        LocalClientIdentifier:            'naLNM4EkYBLxJ510BrNLeyZukJWrAi'

        # use this value instead to test that the verification works.
        #LocalClientIdentifier:            'bogus'

        RS485Port:                        '/dev/ttyAMA1'


        # LocalMeterNumber is the S/N printed on the front cover of the meter.
        LocalMeterNumber:                 '000300081498'

        LocalMeterScalingFactor:          10.0

        # RemoteMeterNumber should match what the seller has for LocalMeterNumber
        # Don't want the seller to just associate a MeterNumber with a ClientIdentifier because future versions of Distributed Charge - GRID
        # may allow the seller to sell energy from multiple meters to the same customer.
        # also, once connected, the seller tells the buyer what MeterNumber they are selling them from and the buyer double checks it is
        # the same one they expected, from prior communication (which may catch a configuration error), before making an initial deposit
        # and finding out that no energy is delivered.
        RemoteMeterNumber:                '000300002157'
        RemoteHost:                       'HostNameOrIPAddress'

        # RemoteFingerPrintToTrust is the seller's public key fingerprint and is printed to the console/log file when first starting grid-seller.py.
        # this needs to be manually shared with the buyer in a trustable way (such as a physical site visit). however, the same value may be shared
        # with multiple buyers by the seller.
        RemoteFingerPrintToTrust:         '9f8fd79dc535d40317705f4683db42bdceb32543caf176bab13696b12626b815'

        # use this value instead to test that the verification works.
        #RemoteFingerPrintToTrust:         'bogus'



        ##### EV related settings ####
        SWCANname:                        'can0'                                  #name of the interface for the single wire can bus, the charge port can bus.
        TWCANname:                        'can1'                                  #name of the interface for the two wire can bus (standard can)




